baseurl: https://afrikaniz3d.netlify.app/
title: Afrikaniz3D Blogfolio
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: 'afrikaniz3d'
googleAnalytics: 'G-068HZ9Y7CD'
params:
  copyright: '&copy; 2024 Afrikaniz3D / Ntobeko Sosibo'
  description: Combination of a blog and portfolio I use to try host as much of my works in one place.
  email: afrikaniz3d@gmail.com
  navlinks:
    - name: About Afrikaniz3D
      url: about/
    - name: Portfolio
      url: portfolio/
      home: yes
    - name: Blender Market
      url: https://blendermarket.com/creators/afrikaniz3d/
    - name: Gumroad
      url: https://afrikaniz3dza.gumroad.com/
    - name: Art Station
      url: https://www.artstation.com/afrikaniz3d/store/
    - name: Patreon
      url: https://patreon.com/afrikaniz3d
    - name: Blogs
      url: post/
    - name: Get in touch
      url: contact/
  sidebarAbout:
    - Data Analyst with expertise in data analytics, visualization, and project management. Proficient in Big Query SQL, RStudio, and Databricks. I am also a CG hobbyist working mostly with Blender3D.
    - From and currently based in South Africa.
    - "#b3d #blender #3dmodeling #3dart #hardsurface #hexesminipack #dataanalytics #datascience #r #powerbi #databricks #python #sql #youtubeseo"
  social:
    email: afrikaniz3d@gmail.com
    facebook: https://www.facebook.com/Afrikaniz3D-103985428323283
    github: https://github.com/afrikaniz3d-za
    instagram: https://www.instagram.com/afrikaniz3d/
    linkedin: https://www.linkedin.com/in/ntobeko-s-040309203
    twitter: https://twitter.com/afrikaniz3d
    whatsapp: https://wa.me/message/USN7BDK3XJC4K1
    youtube: https://youtube.com/c/AFRIKANIZ3D/
  style: graylime

markup:
  goldmark:
    renderer:
      unsafe: true
